# Alembic Configuration File; use 'alembic --help' for command reference.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(asctime)s_%%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to zoneinfo.ZoneInfo()
# Leave the UTC default, else set this to the desired timezone. If dependent
# on server default from the database, leave commented
# timezone =

# max length of characters to apply to the
# "slug" field:
# set to 0 to omit retaining the slug
# alembic revision --autogenerate -m r'add a new column'
# Truncated output filename ->
# ae1027a6acf_add_a_new_column.py
truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# as_revision_base = false

# set to 'false' to allow the environment to control
# sqlalchemy.url, run migrations will not transpose SqlAlchemy.url into
# the engine. This is useful if want to invoke "poetry run alembic" or use tools such
# as alembic_utils
# sqlalchemy.url driver://user:pass@localhost/dbname

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
